site_name:        ProximalOperators.jl
repo_url:         https://github.com/kul-forbes/ProximalOperators.jl
site_description: Description...
site_author:      kul-forbes

theme: bootstrap

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - math

docs_dir: 'build'

pages:
  - Home: index.md
  - Functions: functions.md
  - Calculus rules: calculus.md
  - Prox and gradient: operators.md
  - Demos: demos.md
